name: Testify Project

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 220295
          POSTGRES_DB: testify
        options: >-
          --health-cmd="pg_isready -U postgres -d testify"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "oracle"
          cache: maven

      - name: Wait for PostgreSQL
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          until pg_isready -q -h postgres -p 5432 -U postgres -d testify; do
            sleep 2
          done

      - name: Build with Maven
        working-directory: ./TestifyProject/backend/TestifyProject
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testify
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 220295
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        run: mvn -B clean install

      - name: Run tests
        working-directory: ./TestifyProject/backend/TestifyProject
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testify
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 220295
          SPRING_PROFILES_ACTIVE: test
        run: mvn -B test
